exports.member=function(req,res,next){
    if(req.session.user){
        next();
    }else{
        res.redirect('/');
    }
}
exports.admin=function(req,res,next){
    if(req.session.user.role>50){
        next();
    }else{
        res.redirect('/');
    }
}